[package]
name = "sortcat"
version = "1.0.0"
authors = []

[addresses]
sortcat = '0a63dc1796e0490f76735191f8f7d4380eb34727270bfc19cfd9163baa521c32'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
